### PR TITLE
Rotate dots

### PR DESCRIPTION
**Pull request by dmitrystas**
https://github.com/kozakdenys/qr-code-styling/issues/49

### CODE REVIEW

**Comment by HenkVanMaanen** [comment]
@dmitrystas this can be fixed too by the following code, it needs to be fixed in both QRSVG.ts and QRCanvas.ts: 

WRONG:
`dot.draw(
          xBeginning + i * dotSize,
          yBeginning + j * dotSize,`
          
FIX:
`dot.draw(
          yBeginning + j * dotSize,
          xBeginning + i * dotSize,`

**Comment by HenkVanMaanen** [comment]
See fix here: https://github.com/sallandpioneers/qr-code-styling 

This fork will be maintained until further notice by Salland Pioneers (business).

**Comment by NickStull** [comment]
> @dmitrystas this can be fixed too by the following code, it needs to be fixed in both QRSVG.ts and QRCanvas.ts:
> 
> WRONG: `dot.draw( xBeginning + i * dotSize, yBeginning + j * dotSize,`
> 
> FIX: `dot.draw( yBeginning + j * dotSize, xBeginning + i * dotSize,`

@HenkVanMaanen This works for two of the styles but not the others. It's a great fix in general, but it breaks the dot designs for any design other than square and circle. This is because you are transposing them after the dots are designed. You can see this about 12 lines up. 

`const dot = new QRDot({ context: canvasContext, type: options.dotsOptions.type });`

This is where it styles the dot. Circle and Square don't matter, but the other designs like rounded and classy are designed depending on their neighbor. 

I'm trying to work through the code to see if this can be transposed earlier in the code. No lick so far understanding exactly how it works. But I'll reply when I do.

**Comment by KilianB** [comment]
@NickStull do you still intend on publishing your fix?

**Comment by madmacc** [comment]
@NickStull Any update on publishing this?

**Comment by NickStull** [comment]
@KilianB @madmacc I do have it published but to be honest I've made other changes that I'm not comfortable other people using, only because I'm not confident I didn't introduce bugs. I have not been able to thoroughly test. I'd genuinely feel bad if I caused issues for other devs because I don't fully know if my fix is right. 

with that said, if you'd like to try it out here it is: https://github.com/PlasticPrintersMN/pp-qr-code-styling you can see my fixes in the commits ahead. I still need to change the readme to reflect that this is not the original repo. Basically user beware. I'm still learning.

**Comment by madmacc** [comment]
@NickStull Thanks, understood. I just discovered this issue and I have until the end of the week to resolve it so looking at all options!

**Comment by madmacc** [comment]
@NickStull based on your comment above do you still think @HenkVanMaanen's version would work if just used with square style dots?

**Comment by NickStull** [comment]
@madmacc you'll notice, after getting the dots rotation corrected it messed up the cutout for adding an image to the center. That fix is in here as well. Just to say it outloud, I'm not convinced this is the proper fix for the actual issue. There is an issue with how it's building the qr, but I digress, so far it seems to work.

**Comment by NickStull** [comment]
> @NickStull based on your comment above do you still think @HenkVanMaanen's version would work if just used with square style dots?

@madmacc yes , their fix works if using square only, but you will still need the image cutout fix if you plan to put a logo in the middle.

**Comment by madmacc** [comment]
Another option I saw was this one:
https://github.com/KilianB/styled-qr-code
See: https://github.com/kozakdenys/qr-code-styling/issues/105#issuecomment-1229555378

I will update with what I end up using.

**Comment by madmacc** [comment]
> @KilianB @madmacc I do have it published but to be honest I've made other changes that I'm not comfortable other people using, only because I'm not confident I didn't introduce bugs. I have not been able to thoroughly test. I'd genuinely feel bad if I caused issues for other devs because I don't fully know if my fix is right.
> 
> with that said, if you'd like to try it out here it is: https://github.com/PlasticPrintersMN/pp-qr-code-styling you can see my fixes in the commits ahead. I still need to change the readme to reflect that this is not the original repo. Basically user beware. I'm still learning.

I have tried installing this using `npm install PlasticPrintersMN/pp-qr-code-styling` but it does not create the lib folder just the root files. There is a good chance I am doing something wrong as I have only every installed from www.npmjs.com before.
TinyTake20-09-2022-03-00-33

I did try @HenkVanMaanen's fork and this does work with Android for a square no image QR code but has some issues with one of the qr codes which I am looking into.

**Comment by madmacc** [comment]
Anyone keen on having a go at fixing this? 
Happy to help test but I think it is beyond me to make the fix.

**Comment by kozakdenys** [comment]
Finally merged it, you can find it here https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.6.1
Thanks @dmitrystas for your PR and sorry folks you waited for a merge for so long, I promise not to leave you anymore 😉

**Comment by madmacc** [comment]
@kozakdenys thanks for that! I will give it a try in a bit.

**Pull request merged**
